name: Generate Runner Usage Report

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  analyze-runners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Runner Report
        run: |
          mkdir -p reports
          echo "<html><head><title>Runner Usage Report</title></head><body>" > reports/index.html
          echo "<h2>GitHub Actions Runner Usage Report</h2>" >> reports/index.html
          echo "<table border='1'><tr><th>Workflow</th><th>Runners</th></tr>" >> reports/index.html

          for file in .github/workflows/*.yml; do
            name=$(basename "$file")
            runners=$(yq e '.jobs.*.runs-on' "$file" | grep -v 'null' | sort | uniq | tr '\n' ',' | sed 's/,$//')
            if [ -z "$runners" ]; then
              runners="Not Defined"
            fi
            echo "<tr><td>$name</td><td>$runners</td></tr>" >> reports/index.html
          done

          echo "</table></body></html>" >> reports/index.html

      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: runner-usage-report
          path: reports/index.html
