name: Build on MVS Windows Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, MVS_Windows_Runner_HW]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
