name: Use Shared NuGet Cache

on:
  push:
    branches: [main]

jobs:
  use-cache:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact from Cache repo that is org-nuget-packages
        uses: dawidd6/action-download-artifact@v6
        with:
          name: nuget-cache
          repo: MVSHoneywellOrg/org-nuget-packages
          workflow: cache-nuget.yml
          github_token: ${{ secrets.PAT_TOKEN }}
          path: .nuget/packages

      - name: List NuGet packages
        run: dir .nuget\packages
